# Generated by Django 3.0.3 on 2020-05-21 07:48
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension()
    ]
