# Generated by Django 3.0.3 on 2020-02-17 23:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleguideentry',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='styleguideentry',
            name='section',
            field=models.CharField(blank=True, choices=[('AE', 'A&E'), ('OP', 'Opinion'), ('NW', 'News'), ('SP', 'SPORTS')], default='', max_length=2),
        ),
    ]
