# Generated by Django 3.0.3 on 2020-02-18 00:01

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0002_auto_20200217_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='styleguideentry',
            options={'verbose_name': 'Style Guide Entry', 'verbose_name_plural': 'Style Guide Entries'},
        ),
        migrations.AlterField(
            model_name='styleguideentry',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
