# Generated by Django 3.0.3 on 2020-05-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0002_guide_quicklink_section_styleguideentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleguideentry',
            old_name='section',
            new_name='sections',
        ),
    ]
