# Generated by Django 3.0.3 on 2020-02-18 00:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0003_auto_20200217_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleguideentry',
            name='content_tinymc',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
