# Generated by Django 3.0.3 on 2020-02-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0004_styleguideentry_content_tinymc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='styleguideentry',
            name='section',
        ),
        migrations.AddField(
            model_name='styleguideentry',
            name='section',
            field=models.ManyToManyField(null=True, to='styleguide.Section'),
        ),
    ]
