# Generated by Django 3.0.3 on 2020-02-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0006_auto_20200218_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='styleguideentry',
            name='content_tinymc',
        ),
        migrations.AlterField(
            model_name='styleguideentry',
            name='section',
            field=models.ManyToManyField(blank=True, db_index=True, to='styleguide.Section'),
        ),
    ]
