# Generated by Django 3.0.3 on 2020-02-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0007_auto_20200218_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickLinks',
            new_name='Guide',
        ),
        migrations.RenameModel(
            old_name='Guides',
            new_name='QuickLink',
        ),
    ]
