# Generated by Django 3.0.3 on 2020-02-19 03:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0008_auto_20200218_1914'),
    ]

    operations = [
            TrigramExtension()
    ]
