# Generated by Django 3.0.3 on 2020-05-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0010_auto_20200524_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleguideentry',
            name='title',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
    ]
