# Generated by Django 3.0.3 on 2020-06-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0011_auto_20200531_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
    ]
