# Generated by Django 3.0.3 on 2020-06-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['text']},
        ),
    ]
